// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: products.sql

package database

import (
	"context"
	"database/sql"
)

const getProductVariants = `-- name: GetProductVariants :many
SELECT c.gender, c.category, c.product_type, p.id AS product_id, p.name, p.price, pv.id AS variant_id, pv.color, pv.price_override, pi.image_url
FROM categories c
INNER JOIN products p ON c.id = p.category_id
INNER JOIN product_variants pv ON p.id = pv.product_id
INNER JOIN product_images pi ON pv.id = pi.product_variant_id
WHERE 
  (category = $1 OR NOT $2::bool  ) AND 
  (product_type = $3 OR NOT $4::bool)  AND 
  (gender = $5 OR NOT $6::bool) AND
  (pi.is_primary = FALSE)
GROUP BY p.id, c.id, pv.id, pi.image_url
`

type GetProductVariantsParams struct {
	Category       string
	UseCategory    bool
	ProductType    string
	UseProductType bool
	Gender         Gender
	UseGender      bool
}

type GetProductVariantsRow struct {
	Gender        Gender
	Category      string
	ProductType   string
	ProductID     int32
	Name          string
	Price         sql.NullInt32
	VariantID     int32
	Color         string
	PriceOverride sql.NullInt32
	ImageUrl      string
}

func (q *Queries) GetProductVariants(ctx context.Context, arg GetProductVariantsParams) ([]GetProductVariantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductVariants,
		arg.Category,
		arg.UseCategory,
		arg.ProductType,
		arg.UseProductType,
		arg.Gender,
		arg.UseGender,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductVariantsRow
	for rows.Next() {
		var i GetProductVariantsRow
		if err := rows.Scan(
			&i.Gender,
			&i.Category,
			&i.ProductType,
			&i.ProductID,
			&i.Name,
			&i.Price,
			&i.VariantID,
			&i.Color,
			&i.PriceOverride,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
